GET http://localhost:3333/api HTTP/1.1

###

# Фильм
## Получить список фильмов

GET http://localhost:3333/films HTTP/1.1
Content-Type: application/json

###
## фильм по идентификатору

GET http://localhost:3333/films/633b4fafc6bfae16936bbe69 HTTP/1.1

###
## Список фильмов по жанру

GET http://localhost:3333/films/genre/Crime?limit=2 HTTP/1.1

###
## Список комментариев к фильму

GET http://localhost:3333/films/633b4fafc6bfae16936bbe69/comments HTTP/1.1

###
## Создать новый фильм

POST http://localhost:3333/films HTTP/1.1
Content-Type: application/json

{
  "name": "Вперед в будущее",

  "description": "Просто добавление нового фильма",

  "date": "2033-11-11",

  "genre": "Scifi",

  "released": 2033,

  "rating": 1.0,

  "previewVideoLink": "squre.mp4",

  "videoLink": "squre.mp4",

  "actors": ["Прохоров", "бабушка Прохора", "мама Прошки"],

  "director": "Прохоров",

  "runTime": 13,

  "commentCount": 1,

  "userId": "633b4e5674561e74bc53455e",

  "posterImage": "MyFace.jpg",

  "backgroundImage": "MyBack.jpg",

  "backgroundColor": "#070707"

}

###

## Обновление фильма

PATCH http://localhost:3333/films/6352eb248c06a2d517949dbb HTTP/1.1
Content-Type: application/json

{
  "name": "Ночной дозор 3",
  "description": "Проверка обновления"
}

###
## Удаление фильма

DELETE http://localhost:3333/films/6352eb85df7ba3c3d9ff1a11 HTTP/1.1

###

# Комментарии

## Создание комментария

POST http://localhost:3333/comments HTTP/1.1
Content-Type: application/json

{
  "filmId": "633b4fafc6bfae16936bbe69",
  "comment": "Тестирование добавления комментария",
  "date": "2033-11-11",
  "rating": 9.9,
  "userId": "634c51e9d4cd12f93cd9fe3d"
}


###

## Создание комментария 2

POST http://localhost:3333/comments HTTP/1.1
Content-Type: application/json

{
  "filmId": "633b4fafc6bfae16936bbe84",
  "comment": "Тестирование добавления комментария 3",
  "date": "2022-11-22",
  "rating": 9,
  "userId": "634c51e9d4cd12f93cd9fe3d"
}


###
# Пользователи

## Регистрация пользователя

POST http://localhost:3333/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Джек Востмеркин",
  "email": "jeck8@hacker.net",
  "avatarImage": "JackFace.jpg",
  "password": "password"
}

###
## Авторизация пользователя

POST http://localhost:3333/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "jeck@hacker.net",
  "password": "password"
}

###
